"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

import cloudinary
import cloudinary.uploader
import cloudinary.api

import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# ✅ SECRET KEY
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-i5%#q45(&lrdi0@=2n^o_3@nyjwq*d+@&4jx+pi7w-#1v2zajt"
)

# ✅ DEBUG
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ✅ Render hostname automático
RENDER_HOST = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

# ✅ ALLOWED_HOSTS
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]

if RENDER_HOST:
    ALLOWED_HOSTS.append(RENDER_HOST)

if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]

# ✅ CSRF para Render
CSRF_TRUSTED_ORIGINS = []
if RENDER_HOST:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_HOST}")

# ==========================================================
# ✅ Apps
# ==========================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # ✅ Cloudinary (MEDIA en Render Free)
    "cloudinary_storage",
    "cloudinary",

    "cv",
]

# ==========================================================
# ✅ Middleware
# ==========================================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ✅ static en Render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ==========================================================
# ✅ DATABASE
# ==========================================================
DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    # ✅ SQLite local
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }

# ==========================================================
# ✅ Password validation
# ==========================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==========================================================
# ✅ Internationalization
# ==========================================================
LANGUAGE_CODE = "es-ec"
TIME_ZONE = "America/Guayaquil"
USE_I18N = True
USE_TZ = True

# ==========================================================
# ✅ Static files
# ==========================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ==========================================================
# ✅ CLOUDINARY (MEDIA)
# ==========================================================
# ✅ Cloudinary configurado con variables de entorno
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME", ""),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY", ""),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET", ""),
}

# ✅ IMPORTANTE (Django 6): STORAGES reemplaza DEFAULT_FILE_STORAGE y STATICFILES_STORAGE
STORAGES = {
    # ✅ TODO lo que subas (ImageField/FileField) se va a Cloudinary
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    # ✅ Static files con WhiteNoise
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"

# ✅ Solo local (por si pruebas en tu PC)
if DEBUG:
    MEDIA_ROOT = BASE_DIR / "media"

# ==========================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True
)