# Generated by Django 6.0.1 on 2026-01-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(max_length=50)),
                ('perfilactivo', models.IntegerField()),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(max_length=50)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'datospersonales',
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField()),
                ('descripcioncurso', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
            options={
                'db_table': 'cursosrealizados',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(max_length=50)),
                ('emailempresa', models.CharField(max_length=100)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
            options={
                'db_table': 'experiencialaboral',
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='cv.datospersonales')),
            ],
            options={
                'db_table': 'reconocimientos',
            },
        ),
    ]
