# Generated by Django 6.0.1 on 2026-01-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
