# Generated by Django 6.0.1 on 2026-01-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_datospersonales_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/'),
        ),
    ]
