# Generated by Django 6.0.1 on 2026-01-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_productosacademicos_productoslaborales_ventagarage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoslaborales',
            name='idproductoslaborales',
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='productos/academicos/'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='idproductolaboral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='productos/laborales/'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursos/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/experiencia/'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='nombrerecurso',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='nombreproducto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
