# Generated by Django 6.0.1 on 2026-01-24 01:21

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_remove_productoslaborales_idproductoslaborales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(validators=[cv.models.fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(validators=[cv.models.fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(validators=[cv.models.fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(blank=True, null=True, validators=[cv.models.fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(validators=[cv.models.fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='cursosrealizados',
            constraint=models.CheckConstraint(condition=models.Q(('totalhoras__gte', 0)), name='curso_totalhoras_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='cursosrealizados',
            constraint=models.CheckConstraint(condition=models.Q(('fechafin__gte', models.F('fechainicio'))), name='curso_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='experiencialaboral',
            constraint=models.CheckConstraint(condition=models.Q(('fechafingestion__isnull', True), ('fechafingestion__gte', models.F('fechainiciogestion')), _connector='OR'), name='experiencia_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='ventagarage',
            constraint=models.CheckConstraint(condition=models.Q(('valordelbien__gte', 0)), name='garage_valor_gte_0'),
        ),
    ]
