# Generated by Django 6.0.1 on 2026-01-24 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_cursosrealizados_fechafin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message="El teléfono convencional debe tener 8 dígitos o escribir 'no'.", regex='^(?:\\d{8}|[Nn][Oo])$')]),
        ),
    ]
