# Generated by Django 6.0.1 on 2026-01-24 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_datospersonales_telefonoconvencional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 8 o 10 dígitos numéricos.', regex='^\\d{8}$|^\\d{10}$')]),
        ),
    ]
