# Generated by Django 6.0.1 on 2026-01-24 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_experiencialaboral_telefonocontactoempresarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 8 o 10 dígitos numéricos.', regex='^(?:\\d{8}|\\d{10})$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El teléfono convencional debe tener 8 dígitos o escribir 'no'.", regex='^(?:\\d{8}|[Nn][Oo])$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 8 o 10 dígitos numéricos.', regex='^(?:\\d{8}|\\d{10})$')]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 8 o 10 dígitos numéricos.', regex='^(?:\\d{8}|\\d{10})$')]),
        ),
    ]
