# Generated by Django 6.0.1 on 2026-01-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_cursosrealizados_telefonocontactoauspicia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
    ]
