# Generated by Django 6.0.1 on 2026-01-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_datospersonales_perfilactivo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cursosrealizados',
            name='curso_totalhoras_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='cursosrealizados',
            name='curso_fechas_validas',
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
