# Generated by Django 6.0.1 on 2026-01-24 17:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_remove_cursosrealizados_curso_totalhoras_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados/cursos/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados/experiencia/'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='productos/academicos/'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='productos/laborales/'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados/reconocimientos/'),
        ),
    ]
