# Generated by Django 6.0.1 on 2026-01-25 03:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_alter_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='condicion',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Bueno', 'Bueno')], default='Bueno', max_length=20),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fotoproducto',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='garage/'),
        ),
    ]
