# Generated by Django 6.0.1 on 2026-01-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_ventagarage_condicion_ventagarage_fotoproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
